output   = "./repository"
wipe     = true
no-tests = true

[psql]
  user = "root"
  dbname = "grpc-demo-server"
  host   = "localhost"
  port   = 5432
  pass   = "password"
  sslmode = "disable"
  blacklist = ["schema_migrations"]

[aliases.tables.host_gpus]
  up_plural     = "HostGpus"
  up_singular   = "HostGpu"
  down_plural   = "hostGpus"
  down_singular = "hostGpu"