output   = "./repository"
wipe     = true
no-tests = true

[psql]
  user = "root"
  dbname = "grpc-demo-server"
  host   = "localhost"
  port   = 5432
  pass   = "password"
  sslmode = "disable"
  blacklist = ["schema_migrations"]