// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Disks            string
	GpuModels        string
	GpuServiceMounts string
	GpuServicePorts  string
	GpuServices      string
	HostGpus         string
	HostServices     string
	Hosts            string
	PendingRequests  string
	Requests         string
	Roles            string
	SensorModels     string
	SensorReadings   string
	Sessions         string
	Users            string
}{
	Disks:            "disks",
	GpuModels:        "gpu_models",
	GpuServiceMounts: "gpu_service_mounts",
	GpuServicePorts:  "gpu_service_ports",
	GpuServices:      "gpu_services",
	HostGpus:         "host_gpus",
	HostServices:     "host_services",
	Hosts:            "hosts",
	PendingRequests:  "pending_requests",
	Requests:         "requests",
	Roles:            "roles",
	SensorModels:     "sensor_models",
	SensorReadings:   "sensor_readings",
	Sessions:         "sessions",
	Users:            "users",
}
