// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: gpu_models.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GpuModels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vram             float32                `protobuf:"fixed32,1,opt,name=vram,proto3" json:"vram,omitempty"`
	OctaneBenchScore int64                  `protobuf:"varint,2,opt,name=octane_bench_score,json=octaneBenchScore,proto3" json:"octane_bench_score,omitempty"`
	GpuNo            int64                  `protobuf:"varint,3,opt,name=gpu_no,json=gpuNo,proto3" json:"gpu_no,omitempty"`
	SlotNo           int64                  `protobuf:"varint,4,opt,name=slot_no,json=slotNo,proto3" json:"slot_no,omitempty"`
	Available        int64                  `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	VramFree         float32                `protobuf:"fixed32,6,opt,name=vram_free,json=vramFree,proto3" json:"vram_free,omitempty"`
	Updated          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"`
	Id               string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GpuModels) Reset() {
	*x = GpuModels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GpuModels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuModels) ProtoMessage() {}

func (x *GpuModels) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuModels.ProtoReflect.Descriptor instead.
func (*GpuModels) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{0}
}

func (x *GpuModels) GetVram() float32 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *GpuModels) GetOctaneBenchScore() int64 {
	if x != nil {
		return x.OctaneBenchScore
	}
	return 0
}

func (x *GpuModels) GetGpuNo() int64 {
	if x != nil {
		return x.GpuNo
	}
	return 0
}

func (x *GpuModels) GetSlotNo() int64 {
	if x != nil {
		return x.SlotNo
	}
	return 0
}

func (x *GpuModels) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GpuModels) GetVramFree() float32 {
	if x != nil {
		return x.VramFree
	}
	return 0
}

func (x *GpuModels) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *GpuModels) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateGpuModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vram             float32 `protobuf:"fixed32,1,opt,name=vram,proto3" json:"vram,omitempty"`
	OctaneBenchScore int64   `protobuf:"varint,2,opt,name=octane_bench_score,json=octaneBenchScore,proto3" json:"octane_bench_score,omitempty"`
	GpuNo            int64   `protobuf:"varint,3,opt,name=gpu_no,json=gpuNo,proto3" json:"gpu_no,omitempty"`
	SlotNo           int64   `protobuf:"varint,4,opt,name=slot_no,json=slotNo,proto3" json:"slot_no,omitempty"`
	Available        int64   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	VramFree         float32 `protobuf:"fixed32,6,opt,name=vram_free,json=vramFree,proto3" json:"vram_free,omitempty"`
}

func (x *CreateGpuModelRequest) Reset() {
	*x = CreateGpuModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGpuModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGpuModelRequest) ProtoMessage() {}

func (x *CreateGpuModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGpuModelRequest.ProtoReflect.Descriptor instead.
func (*CreateGpuModelRequest) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGpuModelRequest) GetVram() float32 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *CreateGpuModelRequest) GetOctaneBenchScore() int64 {
	if x != nil {
		return x.OctaneBenchScore
	}
	return 0
}

func (x *CreateGpuModelRequest) GetGpuNo() int64 {
	if x != nil {
		return x.GpuNo
	}
	return 0
}

func (x *CreateGpuModelRequest) GetSlotNo() int64 {
	if x != nil {
		return x.SlotNo
	}
	return 0
}

func (x *CreateGpuModelRequest) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *CreateGpuModelRequest) GetVramFree() float32 {
	if x != nil {
		return x.VramFree
	}
	return 0
}

type CreateGpuModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpu *GpuModels `protobuf:"bytes,1,opt,name=gpu,proto3" json:"gpu,omitempty"`
}

func (x *CreateGpuModelResponse) Reset() {
	*x = CreateGpuModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGpuModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGpuModelResponse) ProtoMessage() {}

func (x *CreateGpuModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGpuModelResponse.ProtoReflect.Descriptor instead.
func (*CreateGpuModelResponse) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGpuModelResponse) GetGpu() *GpuModels {
	if x != nil {
		return x.Gpu
	}
	return nil
}

type UpdateGpuModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vram             *float32 `protobuf:"fixed32,1,opt,name=vram,proto3,oneof" json:"vram,omitempty"`
	OctaneBenchScore *int64   `protobuf:"varint,2,opt,name=octane_bench_score,json=octaneBenchScore,proto3,oneof" json:"octane_bench_score,omitempty"`
	GpuNo            *int64   `protobuf:"varint,3,opt,name=gpu_no,json=gpuNo,proto3,oneof" json:"gpu_no,omitempty"`
	SlotNo           *int64   `protobuf:"varint,4,opt,name=slot_no,json=slotNo,proto3,oneof" json:"slot_no,omitempty"`
	Available        *int64   `protobuf:"varint,5,opt,name=available,proto3,oneof" json:"available,omitempty"`
	VramFree         *float32 `protobuf:"fixed32,6,opt,name=vram_free,json=vramFree,proto3,oneof" json:"vram_free,omitempty"`
	Id               string   `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateGpuModelRequest) Reset() {
	*x = UpdateGpuModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGpuModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGpuModelRequest) ProtoMessage() {}

func (x *UpdateGpuModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGpuModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateGpuModelRequest) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGpuModelRequest) GetVram() float32 {
	if x != nil && x.Vram != nil {
		return *x.Vram
	}
	return 0
}

func (x *UpdateGpuModelRequest) GetOctaneBenchScore() int64 {
	if x != nil && x.OctaneBenchScore != nil {
		return *x.OctaneBenchScore
	}
	return 0
}

func (x *UpdateGpuModelRequest) GetGpuNo() int64 {
	if x != nil && x.GpuNo != nil {
		return *x.GpuNo
	}
	return 0
}

func (x *UpdateGpuModelRequest) GetSlotNo() int64 {
	if x != nil && x.SlotNo != nil {
		return *x.SlotNo
	}
	return 0
}

func (x *UpdateGpuModelRequest) GetAvailable() int64 {
	if x != nil && x.Available != nil {
		return *x.Available
	}
	return 0
}

func (x *UpdateGpuModelRequest) GetVramFree() float32 {
	if x != nil && x.VramFree != nil {
		return *x.VramFree
	}
	return 0
}

func (x *UpdateGpuModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateGpuModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpu *GpuModels `protobuf:"bytes,1,opt,name=gpu,proto3" json:"gpu,omitempty"`
}

func (x *UpdateGpuModelResponse) Reset() {
	*x = UpdateGpuModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGpuModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGpuModelResponse) ProtoMessage() {}

func (x *UpdateGpuModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGpuModelResponse.ProtoReflect.Descriptor instead.
func (*UpdateGpuModelResponse) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGpuModelResponse) GetGpu() *GpuModels {
	if x != nil {
		return x.Gpu
	}
	return nil
}

type GetGpuModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGpuModelRequest) Reset() {
	*x = GetGpuModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGpuModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGpuModelRequest) ProtoMessage() {}

func (x *GetGpuModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGpuModelRequest.ProtoReflect.Descriptor instead.
func (*GetGpuModelRequest) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{5}
}

func (x *GetGpuModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGpuModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpu *GpuModels `protobuf:"bytes,1,opt,name=gpu,proto3" json:"gpu,omitempty"`
}

func (x *GetGpuModelResponse) Reset() {
	*x = GetGpuModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGpuModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGpuModelResponse) ProtoMessage() {}

func (x *GetGpuModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGpuModelResponse.ProtoReflect.Descriptor instead.
func (*GetGpuModelResponse) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{6}
}

func (x *GetGpuModelResponse) GetGpu() *GpuModels {
	if x != nil {
		return x.Gpu
	}
	return nil
}

type GetGpuModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int64 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
}

func (x *GetGpuModelsRequest) Reset() {
	*x = GetGpuModelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGpuModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGpuModelsRequest) ProtoMessage() {}

func (x *GetGpuModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGpuModelsRequest.ProtoReflect.Descriptor instead.
func (*GetGpuModelsRequest) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{7}
}

func (x *GetGpuModelsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGpuModelsRequest) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetGpuModelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpus []*GpuModels `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`
}

func (x *GetGpuModelsResponse) Reset() {
	*x = GetGpuModelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpu_models_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGpuModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGpuModelsResponse) ProtoMessage() {}

func (x *GetGpuModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_models_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGpuModelsResponse.ProtoReflect.Descriptor instead.
func (*GetGpuModelsResponse) Descriptor() ([]byte, []int) {
	return file_gpu_models_proto_rawDescGZIP(), []int{8}
}

func (x *GetGpuModelsResponse) GetGpus() []*GpuModels {
	if x != nil {
		return x.Gpus
	}
	return nil
}

var File_gpu_models_proto protoreflect.FileDescriptor

var file_gpu_models_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x70, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfe, 0x01, 0x0a, 0x09, 0x47, 0x70, 0x75, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x63, 0x74,
	0x61, 0x6e, 0x65, 0x5f, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6f, 0x63, 0x74, 0x61, 0x6e, 0x65, 0x42, 0x65, 0x6e,
	0x63, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x70, 0x75, 0x5f, 0x6e,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67, 0x70, 0x75, 0x4e, 0x6f, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x6c, 0x6f, 0x74, 0x4e, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x72, 0x61, 0x6d, 0x5f, 0x66, 0x72,
	0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x76, 0x72, 0x61, 0x6d, 0x46, 0x72,
	0x65, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x63, 0x74, 0x61, 0x6e, 0x65,
	0x5f, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x6f, 0x63, 0x74, 0x61, 0x6e, 0x65, 0x42, 0x65, 0x6e, 0x63, 0x68, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x70, 0x75, 0x5f, 0x6e, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67, 0x70, 0x75, 0x4e, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6c,
	0x6f, 0x74, 0x4e, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x72, 0x61, 0x6d, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x76, 0x72, 0x61, 0x6d, 0x46, 0x72, 0x65, 0x65, 0x22,
	0x39, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x67, 0x70, 0x75,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x70, 0x75, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x03, 0x67, 0x70, 0x75, 0x22, 0xc5, 0x02, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x00, 0x52, 0x04, 0x76, 0x72, 0x61, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a,
	0x12, 0x6f, 0x63, 0x74, 0x61, 0x6e, 0x65, 0x5f, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x10, 0x6f, 0x63, 0x74,
	0x61, 0x6e, 0x65, 0x42, 0x65, 0x6e, 0x63, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x1a, 0x0a, 0x06, 0x67, 0x70, 0x75, 0x5f, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x02, 0x52, 0x05, 0x67, 0x70, 0x75, 0x4e, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x07,
	0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52,
	0x06, 0x73, 0x6c, 0x6f, 0x74, 0x4e, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x04, 0x52,
	0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a,
	0x09, 0x76, 0x72, 0x61, 0x6d, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x05, 0x52, 0x08, 0x76, 0x72, 0x61, 0x6d, 0x46, 0x72, 0x65, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x76, 0x72, 0x61, 0x6d, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x6f, 0x63, 0x74,
	0x61, 0x6e, 0x65, 0x5f, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x67, 0x70, 0x75, 0x5f, 0x6e, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73,
	0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x6f, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x76, 0x72, 0x61, 0x6d, 0x5f, 0x66, 0x72,
	0x65, 0x65, 0x22, 0x39, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x70, 0x75, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03,
	0x67, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x03, 0x67, 0x70, 0x75, 0x22, 0x24, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x47, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x70, 0x75, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x67, 0x70,
	0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x70, 0x75,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x03, 0x67, 0x70, 0x75, 0x22, 0x44, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x47, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67,
	0x65, 0x22, 0x39, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x70, 0x75, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x67, 0x70, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x70, 0x75,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x04, 0x67, 0x70, 0x75, 0x73, 0x42, 0x15, 0x5a, 0x13,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gpu_models_proto_rawDescOnce sync.Once
	file_gpu_models_proto_rawDescData = file_gpu_models_proto_rawDesc
)

func file_gpu_models_proto_rawDescGZIP() []byte {
	file_gpu_models_proto_rawDescOnce.Do(func() {
		file_gpu_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_gpu_models_proto_rawDescData)
	})
	return file_gpu_models_proto_rawDescData
}

var file_gpu_models_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gpu_models_proto_goTypes = []interface{}{
	(*GpuModels)(nil),              // 0: pb.GpuModels
	(*CreateGpuModelRequest)(nil),  // 1: pb.CreateGpuModelRequest
	(*CreateGpuModelResponse)(nil), // 2: pb.CreateGpuModelResponse
	(*UpdateGpuModelRequest)(nil),  // 3: pb.UpdateGpuModelRequest
	(*UpdateGpuModelResponse)(nil), // 4: pb.UpdateGpuModelResponse
	(*GetGpuModelRequest)(nil),     // 5: pb.GetGpuModelRequest
	(*GetGpuModelResponse)(nil),    // 6: pb.GetGpuModelResponse
	(*GetGpuModelsRequest)(nil),    // 7: pb.GetGpuModelsRequest
	(*GetGpuModelsResponse)(nil),   // 8: pb.GetGpuModelsResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_gpu_models_proto_depIdxs = []int32{
	9, // 0: pb.GpuModels.updated:type_name -> google.protobuf.Timestamp
	0, // 1: pb.CreateGpuModelResponse.gpu:type_name -> pb.GpuModels
	0, // 2: pb.UpdateGpuModelResponse.gpu:type_name -> pb.GpuModels
	0, // 3: pb.GetGpuModelResponse.gpu:type_name -> pb.GpuModels
	0, // 4: pb.GetGpuModelsResponse.gpus:type_name -> pb.GpuModels
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gpu_models_proto_init() }
func file_gpu_models_proto_init() {
	if File_gpu_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gpu_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GpuModels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGpuModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGpuModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGpuModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGpuModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGpuModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGpuModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGpuModelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpu_models_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGpuModelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gpu_models_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gpu_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gpu_models_proto_goTypes,
		DependencyIndexes: file_gpu_models_proto_depIdxs,
		MessageInfos:      file_gpu_models_proto_msgTypes,
	}.Build()
	File_gpu_models_proto = out.File
	file_gpu_models_proto_rawDesc = nil
	file_gpu_models_proto_goTypes = nil
	file_gpu_models_proto_depIdxs = nil
}
